packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@sentry-internal/node-cpu-profiler': set this to true or false
  '@sentry/cli': set this to true or false
  electron: true
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - sharp
