packages:
  - 'apps/api'
  - 'apps/web'
  - 'packages/agents'
  - 'packages/database'
  - 'packages/prompts'
  - 'packages/rag-core'
  - 'packages/types'

allowBuilds:
  '@sentry-internal/node-cpu-profiler': set this to true or false
  '@sentry/cli': true
  '@sentry/node-cpu-profiler': true
  electron: true
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - sharp
